version: '2'
services:
  web:
    build: .
    container_name: order_web
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    networks:
      - default
      - payments_default
    external_links:
      - payments_web:payments.local
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: ec
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1"
      LANG: C.UTF-8
    volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3307:330
networks:
  payments_default:
    external: true
